version: '3.8'

services:
  db:
    image: postgres:17.2-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: power_plant  # This creates the 'power_plant' database on startup
    volumes:
      - ./power_plant_ddl.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init.sql file to run during startup
    ports:
      - "5432:5432"  # Expose PostgreSQL port to the host
    networks:
      - db_network

  power-plant-app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        JAR_PATH: "build/libs/power-plant-0.0.1-SNAPSHOT.jar"  # You can customize this if needed
    ports:
      - "8080:8080"  # Expose port 8080 for the app
    environment:
      SPRING_PROFILES_ACTIVE: "prod"  # Set the profile if needed (e.g., prod, dev)
    restart: unless-stopped  # Ensure the app restarts unless stopped manually
    depends_on:
      - db  # Ensure db service is up before the app starts
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
